### ISSUE TITLE
versionning the vle.conf configuration file

### ISSUE THREAD

**Issue by Chabrier** [vle-forge/vle#351]
In order to have many version of vle installed on the same user account, it could be convenient to distinguish the vle.conf configuration file.

**Comment by quesnel** [comment]
On Thu 11 Oct 18, Patrick Chabrier wrote:
> In order to have many version of vle installed on the same user
> account, it could be convenient to distinguish the vle.conf
> configuration file.

Problem comes from the VLE_COMMAND_VLE_SIMULATION (executable name:
vle-$VLE_ABI_VERSION) [1]. User must use the `--restart` command line
option to rewrite the vle.conf file between VLE 2.0 and VLE 2.1
otherwise, the VLE executable use can be the wrong.

Solutions are:

* suffix `$VLE_HOME/vle.conf`: `vle.conf` for VLE 2.0 and `vle-21.conf`
  for VLE 2.1, `vle-22.conf` for VLE 2.2…
  * The simplest to develop.
  * But, requires to change all the files (`vle.log`, `gvle.log` etc) too.

* add a suffixed sub-directories in the `VLE_HOME` directory. For
  example, `VLE_HOME=/tmp` => `/tmp` for VLE 2.0 (untouched),
  `/tmp/vle-21/` for VLE 2.1, `/tmp/vle-22` for VLE 2.2… VLE 2.0
  untouched and keeps the current behaviour. Start from VLE 2.1, we add
  a sub-directory `vle-21` where we store binary packages, log, conf
  etc.). 
  * Need change and information for user 
  * The least restrictive solution for the future

[1] https://github.com/vle-forge/vle/blob/master/src/vle/utils/ContextSettings.cpp#L74
